### ISSUE TITLE
Russian encoding

### ISSUE THREAD

**Issue by Perevalov** [BorderCloud/SPARQL-JAVA#1]
How can i get a list of entities with russian encoding?

**Comment by BorderCloud** [comment]
Can you give me an example of query with Wikidata or another Sparql Endpoint ?
And the result of this query with russian encoding.

Thanks
Karima

**Comment by Perevalov** [comment]
Here is the query:
`SELECT ?human ?humanLabel
WHERE
{
	?human wdt:P31 wd:Q5 .       #find humans
	?human rdf:type wdno:P40 .   #with at least one P40 (child) statement defined to be "no value"
	SERVICE wikibase:label { bd:serviceParam wikibase:language "ru" }
}`
And the result:

ÐÐ¾Ð¸ÐºÑ, Ð®ÑÐ¸ÐºÐ¾

Ð¥Ð°ÑÑÐ¸, Ð¤ÑÐ¼Ð¸ÐºÐ¾

ÐÐ°Ð½ÑÑÐ»Ð° ÐÐ°ÑÐ¼ÐµÐ½Ð°

Ð¢ÑÐ¸ Ð Ð¸ÑÐ¼Ð°ÑÐ°ÑÐ¸Ð½Ð¸

Ð Ð°Ð´Ð¶Ð¸, ÐÐ¸ÑÐ´Ð¶Ð¸Ð½Ð¸Ñ

ÐÐ°Ð»Ð°Ñ Ð Ð°Ð²Ð°Ð»ÑÐ¼Ð°Ð½Ð°Ð½Ð°

ÐÐ½Ð½ ÐÐ´Ð°Ð»ÑÐ³Ð¾

**Comment by BorderCloud** [comment]
Can you test with this last commit ?

**Comment by Perevalov** [comment]
Works! Thank you!
