### ISSUE TITLE
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier

### ISSUE THREAD

**Issue by langsmith** [BorderCloud/SPARQL-JAVA#2]
Crash when I try to make a Wikidata query

```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
```

```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex) at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit (SSLConnectionSocketFactory.java:146) at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:964)
```

**Comment by langsmith** [comment]
https://stackoverflow.com/a/32313284

https://github.com/marvin-we/steem-java-api-wrapper/issues/146


https://stackoverflow.com/questions/27366430/getting-nosuchfielderror-instance-org-apache-http-message-basicheadervalueparser

**Comment by BorderCloud** [comment]
I found this doc
http://hc.apache.org/httpcomponents-client-4.3.x/android-port.html

You need to use in android this line for http-client in grable : 
```
dependencies {
    compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'
}
```

**Comment by BorderCloud** [comment]
I made a new version for android (only get for the moment).
https://github.com/BorderCloud/SPARQL-ANDROID

**Comment by langsmith** [comment]
Great, thank you @BorderCloud !

**Comment by BorderCloud** [comment]
It"s not the same error. You need to create a new issue and show how to reproduce this error (with an accessible endpoint and query).

**Comment by waning007** [comment]
no i have still error  too
that my logcat

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

I use implementation files('libs/httpcore-4.4.1.jar') ,but is must

**Comment by BorderCloud** [comment]
@waning007 you need to use https://github.com/BorderCloud/SPARQL-ANDROID for Android. Android  doesn't support httpcore.

**Comment by babyeldhose** [comment]
08-15 12:33:29.028 10731-10731/ai.nuralogix.nura E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.nuralogix.nura, PID: 10731
    java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes2.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
        at com.maxmind.geoip2.WebServiceClient.<init>(WebServiceClient.java:139)
        at com.maxmind.geoip2.WebServiceClient.<init>(WebServiceClient.java:100)
        at com.maxmind.geoip2.WebServiceClient$Builder.build(WebServiceClient.java:257)
can any one know what is the issue

**Comment by BorderCloud** [comment]
@babyeldhose Do you test for Android this lib https://github.com/BorderCloud/SPARQL-ANDROID ?
