### ISSUE TITLE
Support customizing user agent

### ISSUE THREAD

**Issue by lucaswerkmeister** [BorderCloud/SPARQL-JAVA#5]
As far as I can tell, this library will currently send the default Apache HttpComponents User-Agent header to the query service (though I haven’t tested it). It should allow users to customize this (and ideally use a default that identifies this particular library).

**Comment by BorderCloud** [comment]
It's done.
Thanks.

**Comment by lucaswerkmeister** [comment]
Support for customizing the user agent seems to have vanished in the new version (eb8132d7ae6f70b18815f5aa0845ca73f3d85ece).

**Comment by BorderCloud** [comment]
You can propose a pull request or I will fix it in the next version.

Thanks
