### ISSUE TITLE
Support databases behind OAuth 2.0

### ISSUE THREAD

**Issue by BorderCloud** [BorderCloud/SPARQL-JAVA#9]
TODO: ask the token before sending the SPARQL query:
- https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
- https://www.oauth.com/oauth2-servers/access-tokens/password-grant/

The token will be revoked when the class is deleted by the garbage collector.

If the token is obsolete, request it again.

**Comment by seebi** [comment]
how to get a keycloak backed token with password flow:

```
curl -X POST  -d "grant_type=password&client_id=YOURCLIENTHERE&username=YOURUSERHERE&password=YOURPASSHERE"  https://YOURKEYCLOAK/auth/realms/cmem/protocol/openid-connect/token
```

how to get a keycloak backed token with client_credential flow:

```
curl -X POST  -d "grant_type=client_credentials&client_id=YOURCLIENTHERE&client_secret=YOURCLIENTSECRETHERE"  https://YOURKEYCLOAK/auth/realms/cmem/protocol/openid-connect/token```

**Comment by seebi** [comment]
tested and worked nicely
